version: '3.8'
services:
  database:
    image: mongo:6.0
    container_name: database
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    command: --port ${DATABASE_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASS}
    networks:
      - term-tracker-network

  redis:
    image: redis:6.0
    container_name: redis
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - term-tracker-network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}
    ports:
      - '8081:8081'
    networks:
      - term-tracker-network
    depends_on:
      - redis

  app:
    container_name: api-term-tracker
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - REDIS_HOST=localhost
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
      - redis
      - redis-commander
    networks:
      - term-tracker-network

networks:
  term-tracker-network:
    driver: bridge
